// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Traveller.API.Data.DbContexts;

#nullable disable

namespace Traveller.API.Migrations
{
    [DbContext(typeof(TravellerDbContext))]
    [Migration("20231011231604_Create Skill and SkillSpecialization Tables")]
    partial class CreateSkillandSkillSpecializationTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("Traveller.API.Data.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DEX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EDU")
                        .HasColumnType("INTEGER");

                    b.Property<int>("END")
                        .HasColumnType("INTEGER");

                    b.Property<int>("INT")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SOC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("STR")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Traveller.API.Data.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Traveller.API.Data.Entities.SkillSpecialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("skillSpecializations");
                });

            modelBuilder.Entity("Traveller.API.Data.Entities.SkillSpecialization", b =>
                {
                    b.HasOne("Traveller.API.Data.Entities.Skill", null)
                        .WithMany("SkillSpecializations")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Traveller.API.Data.Entities.Skill", b =>
                {
                    b.Navigation("SkillSpecializations");
                });
#pragma warning restore 612, 618
        }
    }
}
