// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Traveller.API.Data.DbContexts;

#nullable disable

namespace Traveller.API.Migrations
{
    [DbContext(typeof(TravellerDbContext))]
    [Migration("20231012021447_Skill Seeding")]
    partial class SkillSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("Traveller.API.Data.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DEX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EDU")
                        .HasColumnType("INTEGER");

                    b.Property<int>("END")
                        .HasColumnType("INTEGER");

                    b.Property<int>("INT")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SOC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("STR")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Traveller.API.Data.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBackgroundSkill")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsBackgroundSkill = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            IsBackgroundSkill = false,
                            Name = ""
                        },
                        new
                        {
                            Id = 3,
                            IsBackgroundSkill = true,
                            Name = "Animals"
                        },
                        new
                        {
                            Id = 4,
                            IsBackgroundSkill = true,
                            Name = "Art"
                        },
                        new
                        {
                            Id = 5,
                            IsBackgroundSkill = false,
                            Name = "Astrogation"
                        },
                        new
                        {
                            Id = 6,
                            IsBackgroundSkill = true,
                            Name = "Athletics"
                        },
                        new
                        {
                            Id = 7,
                            IsBackgroundSkill = false,
                            Name = "Broker"
                        },
                        new
                        {
                            Id = 8,
                            IsBackgroundSkill = true,
                            Name = "Carouse"
                        },
                        new
                        {
                            Id = 9,
                            IsBackgroundSkill = false,
                            Name = "Deception"
                        },
                        new
                        {
                            Id = 10,
                            IsBackgroundSkill = false,
                            Name = "Diplomat"
                        },
                        new
                        {
                            Id = 11,
                            IsBackgroundSkill = true,
                            Name = "Drive"
                        },
                        new
                        {
                            Id = 12,
                            IsBackgroundSkill = true,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 13,
                            IsBackgroundSkill = false,
                            Name = "Explosives"
                        },
                        new
                        {
                            Id = 14,
                            IsBackgroundSkill = true,
                            Name = "Flyer"
                        },
                        new
                        {
                            Id = 15,
                            IsBackgroundSkill = false,
                            Name = "Gambler"
                        },
                        new
                        {
                            Id = 16,
                            IsBackgroundSkill = false,
                            Name = "Gunner"
                        },
                        new
                        {
                            Id = 17,
                            IsBackgroundSkill = false,
                            Name = "Gun Combat"
                        },
                        new
                        {
                            Id = 18,
                            IsBackgroundSkill = false,
                            Name = "Heavy Weapons"
                        },
                        new
                        {
                            Id = 19,
                            IsBackgroundSkill = false,
                            Name = "Investigate"
                        },
                        new
                        {
                            Id = 20,
                            IsBackgroundSkill = false,
                            Name = "Jack-Of-All-Trades"
                        },
                        new
                        {
                            Id = 21,
                            IsBackgroundSkill = true,
                            Name = "Language"
                        },
                        new
                        {
                            Id = 22,
                            IsBackgroundSkill = false,
                            Name = "Leadership"
                        },
                        new
                        {
                            Id = 23,
                            IsBackgroundSkill = true,
                            Name = "Mechanic"
                        },
                        new
                        {
                            Id = 24,
                            IsBackgroundSkill = true,
                            Name = "Medic"
                        },
                        new
                        {
                            Id = 25,
                            IsBackgroundSkill = false,
                            Name = "Melee"
                        },
                        new
                        {
                            Id = 26,
                            IsBackgroundSkill = false,
                            Name = "Navigation"
                        },
                        new
                        {
                            Id = 27,
                            IsBackgroundSkill = false,
                            Name = "Persuade"
                        },
                        new
                        {
                            Id = 28,
                            IsBackgroundSkill = false,
                            Name = "Pilot"
                        },
                        new
                        {
                            Id = 29,
                            IsBackgroundSkill = true,
                            Name = "Profession"
                        },
                        new
                        {
                            Id = 30,
                            IsBackgroundSkill = false,
                            Name = "Recon"
                        },
                        new
                        {
                            Id = 31,
                            IsBackgroundSkill = true,
                            Name = "Science"
                        },
                        new
                        {
                            Id = 32,
                            IsBackgroundSkill = true,
                            Name = "Seafarer"
                        },
                        new
                        {
                            Id = 33,
                            IsBackgroundSkill = false,
                            Name = "Stealth"
                        },
                        new
                        {
                            Id = 34,
                            IsBackgroundSkill = false,
                            Name = "Steward"
                        },
                        new
                        {
                            Id = 35,
                            IsBackgroundSkill = true,
                            Name = "Streetwise"
                        },
                        new
                        {
                            Id = 36,
                            IsBackgroundSkill = true,
                            Name = "Survival"
                        },
                        new
                        {
                            Id = 37,
                            IsBackgroundSkill = false,
                            Name = "Tactics"
                        },
                        new
                        {
                            Id = 38,
                            IsBackgroundSkill = true,
                            Name = "Vacc Suit"
                        });
                });

            modelBuilder.Entity("Traveller.API.Data.Entities.SkillSpecialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("skillSpecializations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Handling",
                            SkillId = 3
                        },
                        new
                        {
                            Id = 2,
                            Name = "Veterinary",
                            SkillId = 3
                        },
                        new
                        {
                            Id = 3,
                            Name = "Training",
                            SkillId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Performer",
                            SkillId = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "Holography",
                            SkillId = 4
                        },
                        new
                        {
                            Id = 6,
                            Name = "Instrument",
                            SkillId = 4
                        },
                        new
                        {
                            Id = 7,
                            Name = "Visual Media",
                            SkillId = 4
                        },
                        new
                        {
                            Id = 8,
                            Name = "Write",
                            SkillId = 4
                        },
                        new
                        {
                            Id = 9,
                            Name = "Dexterity",
                            SkillId = 6
                        },
                        new
                        {
                            Id = 10,
                            Name = "Endurance",
                            SkillId = 6
                        },
                        new
                        {
                            Id = 11,
                            Name = "Strength",
                            SkillId = 6
                        },
                        new
                        {
                            Id = 12,
                            Name = "Hovercraft",
                            SkillId = 11
                        },
                        new
                        {
                            Id = 13,
                            Name = "Mole",
                            SkillId = 11
                        },
                        new
                        {
                            Id = 14,
                            Name = "Track",
                            SkillId = 11
                        },
                        new
                        {
                            Id = 15,
                            Name = "Walker",
                            SkillId = 11
                        },
                        new
                        {
                            Id = 16,
                            Name = "Wheel",
                            SkillId = 11
                        },
                        new
                        {
                            Id = 17,
                            Name = "Comms",
                            SkillId = 12
                        },
                        new
                        {
                            Id = 18,
                            Name = "Computers",
                            SkillId = 12
                        },
                        new
                        {
                            Id = 19,
                            Name = "Remote Ops",
                            SkillId = 12
                        },
                        new
                        {
                            Id = 20,
                            Name = "Sensors",
                            SkillId = 12
                        },
                        new
                        {
                            Id = 21,
                            Name = "Airship",
                            SkillId = 14
                        },
                        new
                        {
                            Id = 22,
                            Name = "Grav",
                            SkillId = 14
                        },
                        new
                        {
                            Id = 23,
                            Name = "Ornithopter",
                            SkillId = 14
                        },
                        new
                        {
                            Id = 24,
                            Name = "Rotor",
                            SkillId = 14
                        },
                        new
                        {
                            Id = 25,
                            Name = "Wing",
                            SkillId = 14
                        },
                        new
                        {
                            Id = 26,
                            Name = "Turret",
                            SkillId = 16
                        },
                        new
                        {
                            Id = 27,
                            Name = "Ortillery",
                            SkillId = 16
                        },
                        new
                        {
                            Id = 28,
                            Name = "Screen",
                            SkillId = 16
                        },
                        new
                        {
                            Id = 29,
                            Name = "Capital",
                            SkillId = 16
                        },
                        new
                        {
                            Id = 30,
                            Name = "Archaic",
                            SkillId = 17
                        },
                        new
                        {
                            Id = 31,
                            Name = "Energy",
                            SkillId = 17
                        },
                        new
                        {
                            Id = 32,
                            Name = "Slug",
                            SkillId = 17
                        },
                        new
                        {
                            Id = 33,
                            Name = "Artillery",
                            SkillId = 18
                        },
                        new
                        {
                            Id = 34,
                            Name = "Portable",
                            SkillId = 18
                        },
                        new
                        {
                            Id = 35,
                            Name = "Vehicle",
                            SkillId = 18
                        },
                        new
                        {
                            Id = 36,
                            Name = "Galanglic",
                            SkillId = 21
                        },
                        new
                        {
                            Id = 37,
                            Name = "Vilani",
                            SkillId = 21
                        },
                        new
                        {
                            Id = 38,
                            Name = "Zdetl",
                            SkillId = 21
                        },
                        new
                        {
                            Id = 39,
                            Name = "Oynprith",
                            SkillId = 21
                        },
                        new
                        {
                            Id = 40,
                            Name = "Trokh",
                            SkillId = 21
                        },
                        new
                        {
                            Id = 41,
                            Name = "Gvegh",
                            SkillId = 21
                        },
                        new
                        {
                            Id = 42,
                            Name = "Unarmed",
                            SkillId = 25
                        },
                        new
                        {
                            Id = 43,
                            Name = "Blade",
                            SkillId = 25
                        },
                        new
                        {
                            Id = 44,
                            Name = "Bludgeon",
                            SkillId = 25
                        },
                        new
                        {
                            Id = 45,
                            Name = "Natural",
                            SkillId = 25
                        },
                        new
                        {
                            Id = 46,
                            Name = "Small Craft",
                            SkillId = 28
                        },
                        new
                        {
                            Id = 47,
                            Name = "Spacecraft",
                            SkillId = 28
                        },
                        new
                        {
                            Id = 48,
                            Name = "Capital Ships",
                            SkillId = 28
                        },
                        new
                        {
                            Id = 49,
                            Name = "Belter",
                            SkillId = 29
                        },
                        new
                        {
                            Id = 50,
                            Name = "Biologicals",
                            SkillId = 29
                        },
                        new
                        {
                            Id = 51,
                            Name = "Civil Engineering",
                            SkillId = 29
                        },
                        new
                        {
                            Id = 52,
                            Name = "Construction",
                            SkillId = 29
                        },
                        new
                        {
                            Id = 53,
                            Name = "Hydroponics",
                            SkillId = 29
                        },
                        new
                        {
                            Id = 54,
                            Name = "Polymers",
                            SkillId = 29
                        },
                        new
                        {
                            Id = 55,
                            Name = "Archaeology",
                            SkillId = 31
                        },
                        new
                        {
                            Id = 56,
                            Name = "Astronomy",
                            SkillId = 31
                        },
                        new
                        {
                            Id = 57,
                            Name = "Biology",
                            SkillId = 31
                        },
                        new
                        {
                            Id = 58,
                            Name = "Chemistry",
                            SkillId = 31
                        },
                        new
                        {
                            Id = 59,
                            Name = "Cosmology",
                            SkillId = 31
                        },
                        new
                        {
                            Id = 60,
                            Name = "Cybernetics",
                            SkillId = 31
                        },
                        new
                        {
                            Id = 61,
                            Name = "Economics",
                            SkillId = 31
                        },
                        new
                        {
                            Id = 62,
                            Name = "Genetics",
                            SkillId = 31
                        },
                        new
                        {
                            Id = 63,
                            Name = "History",
                            SkillId = 31
                        },
                        new
                        {
                            Id = 64,
                            Name = "Linguistics",
                            SkillId = 31
                        },
                        new
                        {
                            Id = 65,
                            Name = "Philosophy",
                            SkillId = 31
                        },
                        new
                        {
                            Id = 66,
                            Name = "Physics",
                            SkillId = 31
                        },
                        new
                        {
                            Id = 67,
                            Name = "Planetology",
                            SkillId = 31
                        },
                        new
                        {
                            Id = 68,
                            Name = "Psionicology",
                            SkillId = 31
                        },
                        new
                        {
                            Id = 69,
                            Name = "Psychology",
                            SkillId = 31
                        },
                        new
                        {
                            Id = 70,
                            Name = "Robotics",
                            SkillId = 31
                        },
                        new
                        {
                            Id = 71,
                            Name = "Sophontology",
                            SkillId = 31
                        },
                        new
                        {
                            Id = 72,
                            Name = "Xenology",
                            SkillId = 31
                        },
                        new
                        {
                            Id = 73,
                            Name = "Ocean Ships",
                            SkillId = 32
                        },
                        new
                        {
                            Id = 74,
                            Name = "Personal",
                            SkillId = 32
                        },
                        new
                        {
                            Id = 75,
                            Name = "Sail",
                            SkillId = 32
                        },
                        new
                        {
                            Id = 76,
                            Name = "Submarine",
                            SkillId = 32
                        },
                        new
                        {
                            Id = 77,
                            Name = "Military",
                            SkillId = 37
                        },
                        new
                        {
                            Id = 78,
                            Name = "Naval",
                            SkillId = 37
                        });
                });

            modelBuilder.Entity("Traveller.API.Data.Entities.SkillSpecialization", b =>
                {
                    b.HasOne("Traveller.API.Data.Entities.Skill", null)
                        .WithMany("SkillSpecializations")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Traveller.API.Data.Entities.Skill", b =>
                {
                    b.Navigation("SkillSpecializations");
                });
#pragma warning restore 612, 618
        }
    }
}
